name: warehouse_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  socket_io_client: ^2.0.3+1
  signalr_netcore: ^1.4.1
  url_launcher: ^6.2.5
  flutter_local_notifications: ^17.0.0
  audioplayers: ^5.2.1
  image_picker: ^1.2.1
  file_picker: ^10.3.8
  mime: ^2.0.0
  shared_preferences: ^2.5.4
  json_annotation: ^4.9.0
  provider: ^6.1.5+1
  photo_view: ^0.15.0
  flutter_cached_pdfview: ^0.4.3
  flutter_background: ^1.3.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/alarm.mp3
